GENERAL:
  training_name: pseudo_generator # scene_level_with_fcnet_uppool
  model_name: MultiLabel

DATA:
  pointcloud_data:
    scale: 50 #Voxel size: 1/scale - 2cm
    val_reps: 3 # Number of test views, 1 or more
    batch_size: 4
    elastic_deformation: True
  label: scene_level
  has_text: False

STRUCTURE:
  pointcloud_model:
    name: SparseConvFCNetDirectUpPool
    m: 16 # 16 or 32
    dimension: 3
    full_scale: 4096
    block_reps: 2 #Conv block repetition factor: 1 or 2
    residual_blocks: True #True or False
  loss: 
    Classification: True

Training:
  epochs: 512

PSEUDO_LABEL:
  path: dataset/ScanNet/pseudo_label_all
  suffix: _pseudo_label.pth
  threshold: 0.71
  progressbar: True
  adopt_all_labels: True