GENERAL:
  training_name: train_with_gan
  model_name: MultiLabel

DATA:
  pointcloud_data:
    scale: 50 #Voxel size: 1/scale - 2cm
    val_reps: 3 # Number of test views, 1 or more
    batch_size: 4
    elastic_deformation: False
    num_points_sampled: 40000
  label: scene_level
  in_radius: 2
  has_text: False

STRUCTURE:
  pointcloud_model:
    name: SparseConvFCNetDirectUpPoolLight
    m: 16 # 16 or 32
    dimension: 3
    full_scale: 4096
    block_reps: 2 #Conv block repetition factor: 1 or 2
    residual_blocks: True #True or False
  projector:
    mask_channels: 1
    mask_res: 64
    render_view: HWZ
  loss: 
    Classification: True
    Gan: Gan #WGanGP
    gan_name: NaiiveCNN

Training:
  epochs: 512
  lr: 0.004
  dis_lr: 0.0001