GENERAL:
  training_name: subcloud_level_with_fcnet_baseline_finer
  model_name: MultiLabel

DATA:
  pointcloud_data:
    scale: 50 #Voxel size: 1/scale - 2cm
    val_reps: 1 # Number of test views, 1 or more
    batch_size: 10
    elastic_deformation: False
  label: subcloud
  in_radius: 2
  has_text: False

STRUCTURE:
  pointcloud_model:
    name: SparseConvFCNet
    m: 16 # 16 or 32
    dimension: 3
    full_scale: 4096
    block_reps: 2 #Conv block repetition factor: 1 or 2
    residual_blocks: True #True or False
  loss: 
    Classification: True

Training:
  epochs: 1024