GENERAL:
  training_name: scene_level_with_text
  model_name: MultiLabelContrastive

DATA:
  pointcloud_data:
    scale: 20 #Voxel size: 1/scale - 5cm
    val_reps: 1 # Number of test views, 1 or more
    batch_size: 16
    elastic_deformation: False
  label: scene_level
  has_text: True
  text_data:
    max_seq_len: 120
    cropped_texts: 10

STRUCTURE:
  pointcloud_model:
    name: SparseConvUNet
    m: 16 # 16 or 32
    dimension: 3
    full_scale: 4096
    block_reps: 1 #Conv block repetition factor: 1 or 2
    residual_blocks: False #True or False
  text_model:
    name: TextTransformer
    context_length: 120
    width: 256
    layers: 12
    vocab_size: 49408
  loss: 
    Classification: True
    TextContrastive: True

Training:
  epochs: 512