GENERAL:
  training_name: scene_level_with_fcnet_without_text
  model_name: MultiLabel

DATA:
  pointcloud_data:
    scale: 20 #Voxel size: 1/scale - 5cm
    val_reps: 1 # Number of test views, 1 or more
    batch_size: 8
    elastic_deformation: False
  label: scene_level
  has_text: False

STRUCTURE:
  pointcloud_model:
    name: SparseConvFCNet
    m: 16 # 16 or 32
    residual_blocks: False #True or False
    block_reps: 1 #Conv block repetition factor: 1 or 2
  loss: 
    Classification: True

Training:
  epochs: 1024