GENERAL:
  training_name: scene_level_with_finer_detail
  model_name: MultiLabelContrastive

DATA:
  pointcloud_data:
    scale: 50 #Voxel size: 1/scale - 5cm
    val_reps: 1 # Number of test views, 1 or more
    batch_size: 16
    elastic_deformation: False
  label: scene_level
  has_text: True
  text_data:
    max_seq_len: 120
    cropped_texts: 10

STRUCTURE:
  pointcloud_model:
    name: SparseConvUNet
    m: 16 # 16 or 32
    residual_blocks: True #True or False
    block_reps: 2 #Conv block repetition factor: 1 or 2
  text_model:
    name: TextTransformer
    width: 256
    vocab_size: 49408
    context_length: 120
    layers: 9
  loss: 
    Classification: True
    TextContrastive: True

Training:
  epochs: 512