GENERAL:
  training_name: test
  model_name: MultiLabelContrastive

DATA:
  pointcloud_data:
    scale: 20 #Voxel size: 1/scale - 5cm
    val_reps: 1 # Number of test views, 1 or more
    batch_size: 8
    elastic_deformation: False
  text_data:
    max_seq_len: 120
    cropped_texts: 10

STRUCTURE:
  pointcloud_model:
    name: SparseConvFCNetEncoder
    m: 16 # 16 or 32
    residual_blocks: False #True or False
    block_reps: 1 #Conv block repetition factor: 1 or 2
  text_model:
    name: TextTransformer
    width: 256
    vocab_size: 49408
    context_length: 120
    layers: 12
  loss: 
    Classification: True
    TextContrastive: True

Training:
  epochs: 1024