GENERAL:
  training_name: scene_level_with_fcnet_baseline_much_finer
  model_name: MultiLabel

DATA:
  pointcloud_data:
    scale: 100 #Voxel size: 1/scale - 1cm
    val_reps: 2 # Number of test views, 1 or more
    batch_size: 6
    elastic_deformation: False
  label: scene_level
  has_text: False

STRUCTURE:
  pointcloud_model:
    name: SparseConvFCNet
    m: 16 # 16 or 32
    dimension: 3
    full_scale: 4096
    block_reps: 2 #Conv block repetition factor: 1 or 2
    residual_blocks: True #True or False
  loss: 
    Classification: True

Training:
  epochs: 512